@startuml
' Diagrama de classes g2
skinparam classAttributeIconSize 0

class AplicativoBemEstar

class Usuario {
    -id
    -nome
    -email
    -funcao
}

class Guia {
    -tipo
    -mensagem
}

class Meditacao {
    -titulo
    -duracao
    -descricao
}

class TecnicaRespiracao {
    -nome
    -intervalos
    -descricao
}

class ServicoExterno {
    -nome
    -categoria
    -dataValidade
    -likes
    -deslikes
}

class Especialista {
    -nome
    -especialidade
    -agenda
}

class Consulta {
    -dataHora
    -especialista
    -link
}

class Feedback {
    -mensagem
    -usuario
    -dataEnvio
}

class Report {
    -mensagem
    -usuario
    -dataEnvio
}

class FeedbackAnom {
    -mensagem
    -dataEnvio
}

class Pausa {
    -duração
    -executada
}

interface DetectorPadraoUso {
    +detectarTempoUso
    +detectarAtividadeRepetitiva
}

AplicativoBemEstar  --  DetectorPadraoUso : monitora
AplicativoBemEstar  --  Usuario : possui
AplicativoBemEstar  --  ServicoExterno : oferece
AplicativoBemEstar  --  Guia : oferece
AplicativoBemEstar  --  FeedbackAnom :recebe
AplicativoBemEstar  --  Pausa :recomenda

Usuario  --  Consulta : marca
Usuario -- Feedback : envia
Usuario  --  Pausa : marca
Usuario  --  Report : envia
Usuario  --  ServicoExterno : omite

Consulta  --  Especialista : realiza

Guia -- Meditacao 
Guia -- TecnicaRespiracao

ServicoExterno -- Feedback : recebe
@enduml
